name: Build All

on:
  workflow_dispatch:
    inputs:
      retroarch_version:
        description: 'RetroArch version tag'
        default: 'v1.22.2'

permissions:
  contents: write

jobs:
  universal:
    uses: ./.github/workflows/build-universal.yml
    with:
      retroarch_version: ${{ inputs.retroarch_version }}

  a30:
    uses: ./.github/workflows/build-a30.yml
    with:
      retroarch_version: ${{ inputs.retroarch_version }}

  miyoomini:
    uses: ./.github/workflows/build-miyoomini.yml
    with:
      retroarch_version: ${{ inputs.retroarch_version }}

  universal32:
    uses: ./.github/workflows/build-universal32.yml
    with:
      retroarch_version: ${{ inputs.retroarch_version }}

  h700:
    uses: ./.github/workflows/build-h700.yml
    with:
      retroarch_version: ${{ inputs.retroarch_version }}

  h700-32:
    uses: ./.github/workflows/build-h700-32.yml
    with:
      retroarch_version: ${{ inputs.retroarch_version }}

  pixel2:
    uses: ./.github/workflows/build-pixel2.yml

  rgds:
    uses: ./.github/workflows/build-rgds.yml
